/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/matters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List matters */
        get: operations["list_matters_api_v1_matters_get"];
        put?: never;
        /** Create matter */
        post: operations["create_matter_api_v1_matters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get matter */
        get: operations["get_matter_api_v1_matters__matter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List collections */
        get: operations["list_collections_api_v1_matters__matter_id__collections_get"];
        put?: never;
        /**
         * Upload collection
         * @description Raw streaming upload: the body is the ZIP file, `Content-Type: application/zip`, and the original file name is sent percent-encoded in `X-Filename`.
         */
        post: operations["upload_collection_api_v1_matters__matter_id__collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get collection */
        get: operations["get_collection_api_v1_matters__matter_id__collections__collection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/collections/{collection_id}/ground-truth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download ground truth */
        get: operations["download_ground_truth_api_v1_matters__matter_id__collections__collection_id__ground_truth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List generations */
        get: operations["list_generations_api_v1_matters__matter_id__generations_get"];
        put?: never;
        /** Request a synthetic export */
        post: operations["create_generation_api_v1_matters__matter_id__generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generation */
        get: operations["get_generation_api_v1_matters__matter_id__generations__generation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matters/{matter_id}/generations/{generation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed generation */
        post: operations["retry_generation_api_v1_matters__matter_id__generations__generation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CollectionGenerationOut */
        CollectionGenerationOut: {
            /** Has Ground Truth */
            has_ground_truth: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Preset */
            preset: string;
            /** Profile */
            profile: string;
            /** Seed */
            seed: number;
        };
        /** CollectionListOut */
        CollectionListOut: {
            /** Items */
            items: components["schemas"]["CollectionOut"][];
        };
        /** CollectionOut */
        CollectionOut: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Conversation Count */
            conversation_count: number;
            /** Entry Count */
            entry_count: number;
            /** Export Date From */
            export_date_from: string | null;
            /** Export Date To */
            export_date_to: string | null;
            generation?: components["schemas"]["CollectionGenerationOut"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Matter Id
             * Format: uuid
             */
            matter_id: string;
            /** Original Filename */
            original_filename: string;
            /** Root Prefix */
            root_prefix: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Source */
            source: string;
        };
        /**
         * CreateGenerationRequest
         * @description Raw input; every rule (and its message) lives in the domain validation.
         */
        CreateGenerationRequest: {
            /** Conversations */
            conversations?: number | null;
            /** Messages */
            messages?: number | null;
            /** Overlap Of Collection Id */
            overlap_of_collection_id?: string | null;
            /** Preset */
            preset?: string | null;
            /** Profile */
            profile?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /** CreateMatterRequest */
        CreateMatterRequest: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** GenerationErrorOut */
        GenerationErrorOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** GenerationListOut */
        GenerationListOut: {
            /** Items */
            items: components["schemas"]["GenerationOut"][];
        };
        /** GenerationOut */
        GenerationOut: {
            /** Collection Id */
            collection_id: string | null;
            /** Conversations */
            conversations: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            error: components["schemas"]["GenerationErrorOut"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Id */
            job_id: string | null;
            /**
             * Matter Id
             * Format: uuid
             */
            matter_id: string;
            /** Messages */
            messages: number;
            /** Overlap Of Collection Id */
            overlap_of_collection_id: string | null;
            /** Preset */
            preset: string;
            /** Profile */
            profile: string;
            /** Progress Messages */
            progress_messages: number;
            /** Seed */
            seed: number;
            /** State */
            state: string;
            /** Total Messages */
            total_messages: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChecks */
        HealthChecks: {
            /**
             * Blob Store
             * @enum {string}
             */
            blob_store: "ok" | "unavailable";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Migrations
             * @enum {string}
             */
            migrations: "ok" | "pending" | "unknown";
        };
        /** HealthResponse */
        HealthResponse: {
            /** Active Workers */
            active_workers: number;
            checks: components["schemas"]["HealthChecks"];
            /** Git Sha */
            git_sha: string;
            /** Migration Revision */
            migration_revision: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /** MatterListOut */
        MatterListOut: {
            /** Items */
            items: components["schemas"]["MatterOut"][];
        };
        /** MatterOut */
        MatterOut: {
            /** Collection Count */
            collection_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Total Size Bytes */
            total_size_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_matters_api_v1_matters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterListOut"];
                };
            };
        };
    };
    create_matter_api_v1_matters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMatterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matter_api_v1_matters__matter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_api_v1_matters__matter_id__collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_collection_api_v1_matters__matter_id__collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_matters__matter_id__collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_ground_truth_api_v1_matters__matter_id__collections__collection_id__ground_truth_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ground-truth file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_generations_api_v1_matters__matter_id__generations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation_api_v1_matters__matter_id__generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_api_v1_matters__matter_id__generations__generation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_generation_api_v1_matters__matter_id__generations__generation_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: string;
                generation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Database or migrations not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
