"""Static vocabulary used to render realistic but fully synthetic content."""

from __future__ import annotations

FIRST_NAMES = (
    "Alice",
    "Bruno",
    "Carla",
    "Daniel",
    "Elena",
    "Felipe",
    "Grace",
    "Hugo",
    "Irene",
    "Jorge",
    "Karen",
    "Lucas",
    "Marta",
    "Nuno",
    "Olivia",
    "Paulo",
    "Quinn",
    "Rita",
    "Sergio",
    "Tania",
    "Ulisses",
    "Vera",
    "Walter",
    "Ximena",
    "Yara",
    "Zeca",
    "Amir",
    "Beatriz",
    "Caio",
    "Diana",
)
LAST_NAMES = (
    "Almeida",
    "Barros",
    "Carvalho",
    "Duarte",
    "Esteves",
    "Ferraz",
    "Gomes",
    "Henriques",
    "Ibrahim",
    "Junqueira",
    "Klein",
    "Lopes",
    "Moreira",
    "Nogueira",
    "Oliveira",
    "Pereira",
    "Queiroz",
    "Ribeiro",
    "Santos",
    "Teixeira",
    "Uchoa",
    "Vieira",
    "Weber",
    "Xavier",
)
ADJECTIVES = (
    "alpha",
    "bright",
    "calm",
    "daily",
    "early",
    "fast",
    "global",
    "hidden",
    "internal",
    "joint",
    "key",
    "late",
    "main",
    "new",
    "open",
    "prime",
    "quick",
    "regional",
    "shared",
    "team",
)
NOUNS = (
    "billing",
    "contracts",
    "design",
    "engineering",
    "finance",
    "growth",
    "hiring",
    "incidents",
    "legal",
    "marketing",
    "ops",
    "planning",
    "product",
    "quality",
    "research",
    "sales",
    "security",
    "support",
    "training",
    "updates",
)
BOT_NAMES = (
    "deploybot",
    "alertmanager",
    "standup-helper",
    "jira-sync",
    "calendar-bot",
    "gitlinker",
    "build-watcher",
    "polls",
)
SENTENCES = (
    "Morning everyone, quick sync at 10 today.",
    "Can someone review the latest draft before noon?",
    "I uploaded the revised numbers to the shared folder.",
    "Looks good to me, shipping it this afternoon.",
    "We should double check the contract language on clause 7.",
    "Thanks for the update, that clears things up.",
    "Heads up: the staging environment will be down for maintenance tonight.",
    "Does anyone have the notes from yesterday's meeting?",
    "I will take this one and report back tomorrow.",
    "The customer replied and asked for a revised timeline.",
    "Let us move the discussion to the thread to keep this channel tidy.",
    "Reminder that the quarterly review is next Tuesday.",
    "Great catch, I have fixed the typo in the summary.",
    "We are blocked on access to the vendor portal, ticket opened.",
    "Can we get a second pair of eyes on the invoice reconciliation?",
    "The deployment finished without errors.",
    "Please share your availability for the onboarding session.",
    "I think we need another iteration on the proposal.",
    "All set on my side, waiting for confirmation from legal.",
    "Sharing the agenda for the planning workshop.",
    "That is a fair point, let us revisit it after the break.",
    "Lunch is on me if we hit the milestone this week.",
    "I will be out on Friday, ping me if anything urgent comes up.",
    "The dashboard numbers look off for the last two days.",
    "Approved. Please proceed with the next step.",
    "Thanks all, closing this out.",
    "Not sure I follow, could you add some context?",
    "The audit request came in again, collecting the documents now.",
    "Pushed a small fix, CI is running.",
    "Let me know if the new template works for you.",
)
EMOJI = ("thumbsup", "eyes", "tada", "white_check_mark", "pray", "rocket", "heart", "100")
FILE_TYPES = (
    ("report.pdf", "application/pdf", "pdf"),
    ("budget.xlsx", "application/vnd.ms-excel", "xlsx"),
    ("screenshot.png", "image/png", "png"),
    ("notes.txt", "text/plain", "text"),
    ("slides.pptx", "application/vnd.ms-powerpoint", "pptx"),
)
LINK_LABELS = ("docs", "ticket", "dashboard", "spec", "board", "wiki")
